---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
for(file in list.files("R")) source(file.path("R", file))
library(sp)
library(ggplot2)
```

# Objective

Create a 

# Data 

Dummy data

```{r}
set.seed(123)
df <- dplyr::tibble(
  id = 1:40, 
  group = c(rep(1, 4), rep(2, 4), rep(3, 12), rep(4, 20)), 
  org = sample(c("A", "B", "C", "D"), 40, TRUE, c(0.5, 0.2, 0.2, 0.1))
  )

df |>
  dplyr::group_by(org) |>
  dplyr::count()
```

# Method

Create a grid of hexagon

```{r}
dx <- ceiling(sqrt(nrow(df)))
dy <- dx

cellsize <- 1
C <- hex_side(cellsize)
A <- sin(deg2rad(30)) * C
B <- sin(deg2rad(60)) * C

hexAcross <- ceiling(dx/(B*2)) # This calculation may not be necessary could just use dx
hexUp <- ceiling(dy/((A+C)))

offset_x_start <- 0
offset_y_start <- 0
offset_x_end <- offset_x_start + hexAcross
offset_y_end <- offset_y_start + hexUp

hex_grid <- draw_hexTiles(
  cellsize, offset_x_start, offset_x_end, 
  offset_y_start, offset_y_end
  )

plot(hex_grid)
length(hex_grid)

```

Calculate the distance of each tile from the centre.

```{r}
# Get the centre hex
grid_centre <- rgeos::gCentroid(hex_grid)
hex_grid_centre_id <- over(grid_centre, hex_grid)$id
hex_grid_centre <- hex_grid[hex_grid@data$id == hex_grid_centre_id ,]
plot(rgeos::gCentroid(hex_grid_centre), add = TRUE)

# get centroids of hexes
hex_grid_centroids <- rgeos::gCentroid(hex_grid, byid = TRUE) |> 
  as.data.frame() |>
  dplyr::rename(x1 = x, y1 = y)

hex_grid_centre_centroid <- rgeos::gCentroid(hex_grid_centre) |> 
  as.data.frame() |>
  dplyr::rename(x2 = x, y2 = y)

# calculate distance between centre hex and other hexes
d <- function(x1,x2, y1, y2){
  sqrt((x2-x1)^2 + (y2-y1)^2)
}

distance <- hex_grid_centroids |>
  dplyr::bind_cols(hex_grid_centre_centroid) |>
  dplyr::mutate(distance = d(x1, x2, y1, y2)) |>
  dplyr::pull(distance)

hex_grid@data <- cbind(hex_grid@data, hex_grid_centroids)

hex_grid@data$distance_from_centre <- distance
hex_grid@data$rank <- rank(distance, ties.method = "first")


```

Minimise the distance from the centre based on order.

```{r}
ggplot(fortify(hex_grid)) + 
  geom_polygon(aes(long, lat, group = id), fill = NA, colour = "black") +
  geom_text(data = hex_grid@data, aes(label = rank, x = x1, y = y1))
```

